### ISSUE TITLE
March is doubled and October does not appear while navigating prev / next month

### ISSUE THREAD

**Issue by MacKentoch** [bradberger/angular-material-calendar#35] opened 2015-11-22 07:35 UTC
Hi, 

Before starting explaining my issue, `let me congratulate you for this super nice work` :+1: 

I encounter this issue : 
- **March month is doubled** (*I navigate February to March then March again then April*).
- **October does not appear** (*I navigate from September to November*) — should a consequence of March bug —.
- occurs both calendar and agenda views
- not sure it is relevant but I'm in GMT+2 zone
- it is not related to date event binding since it occurs even if no data are bound
- I updated to latest release and it did not fix this issue

It is 99% chance related to leap year but I had a `fast check` on your `Calendar service` and I don't see what is wrong.

UPDATE : 

**It seems like it is month label issue** since if I check previous and next month data while navigating all seems correct : 

```javascript
	prevMonth(data) {
		console.info(`you clicked (prev) month ${data.month} ${data.year}`);
  }
	
	nextMonth(data) {
		console.info(`you clicked (next) month ${data.month} ${data.year}`);
	}	

```

When september label next/prev tells me : 
```bash
 you clicked (next) month 10 2015
```
Thank you in advance for your help / advices.

**Comment by bradberger** [comment] 2015-11-23 19:36
Sorry I'm behind getting to this, we just had our second child so I'm swamped between client work and home work, I'll try to get to this ASAP, just might be a few days. 

Just in advance to ask, I'm assuming you're using the latest version? I'm assuming so, but just thought I'd ask as there was one version a bit back that had some issues with incorrect use of one-time bindings as so things weren't updating as they should.

**Comment by MacKentoch** [comment] 2015-11-23 20:10
**Congratulations for your child!**
Don't feel in a hurry for that, you have really more important things to do.

Don't worry, I will investigate more on my side.

Thank you for reply!

**Comment by bradberger** [comment] 2015-11-24 08:26
Awesome, thanks. If you happen to figure it out in the meantime, PR's are always most welcome :smile:

**Comment by MacKentoch** [comment] 2015-11-25 12:33
Until now, it seems like it only occurs on my project.
You master branch version is ok and I guess all your previous releases are ok too.

I suspected magnification process but nope.
Maybe something's wrong happens on my project with jspm bundle sfx (I work on ES6 but nearly sure it is not related at all).

I keep on investigating.

**Comment by bradberger** [comment] 2015-12-02 07:56
@MacKentoch Curious if you've come across anything yet. I haven't been able to reproduce yet here, so I'm kind of at a loss right now as to what it could be. Is there anything you can direct me to in an attempt to reproduce it - some kind of sample, etc., that's reproducible?

**Comment by MacKentoch** [comment] 2015-12-03 04:54
@bradberger **you can close this bug since I'm pretty sure it does not come from your calendar**. 
>It only occurs on my project and I feel like it comes on my from my implementation.

I did not go further into my issue's debug since I have to finish a lot of tasks first.
When time has come, I will debug seriously my calendar implementation.

I will give you a feedback then.

**Comment by bradberger** [comment] 2015-12-03 22:04
@MacKentoch Okay, thanks for the update. I'll close it now, but if you figure out what the issue is and maybe we can update things for others who might experience your issue in the future let me know. Thanks!

**Closed by bradberger** 2015-12-03 22:04 UTC
Labels: bug, cant-reproduce
