### ISSUE TITLE
Start day/week is off.

### ISSUE THREAD

**Issue by pulpfree** [bradberger/angular-material-calendar#2] opened 2015-05-29 17:47 UTC
Really like this app you created and looks to be exactly what I am looking for. However I thought I should point an issue I noticed after cloning/building. Your start day is on a row by itself and the last week is a day short. See attached screenshot for explanation.

![angular-material_screenshot](https://cloud.githubusercontent.com/assets/589916/7888802/22cc366c-0609-11e5-82aa-437b3cea7df3.png)

**Comment by bradberger** [comment] 2015-06-01 20:07
Oh, that sure doesn't look right. :frowning: 

Thanks for pointing it out. I've not noticed that in the projects I've used it in so far. Will check it out when I get a chance. Might end up asking for some more details later on if I can't reproduce it.

**Comment by pulpfree** [comment] 2015-06-04 13:52
I found the problem in line 65 of angular-material-calendar.js:
`offset = first.getTimezoneOffset() * -60000;`
I ended up doing a rewrite of the service with inspiration from the angular-ui project.

**Comment by bradberger** [comment] 2015-06-17 06:39
@pulpfree How is the rewrite working out? Is it something that you've published or would like to contribute? This was a project just to scratch an itch, and would be happy to include any improvements you have and even add you to the repository.

**Comment by Jcurrie314** [comment] 2015-06-23 19:52
I fixed it by simply removing the multiplying factor on the timezone offset:

` i =  n.getTimezoneOffset(), ` ....

**Comment by bradberger** [comment] 2015-06-24 19:20
Thanks for the update. Going to look into that when I get a chance... otherwise feel free to submit a PR if you happen to beat me to it.

**Comment by pulpfree** [comment] 2015-06-25 12:57
@bradberger the re-write for the service (with inspiration taken from angular-ui) is working very well. To provide a backdrop, I needed a calendar to work with an existing project built with angular material to display/manage events from the google calendar api. Currently writing a service in golang to interface with googles api to manage events.

I'd be happy to contribute, I can put together a PR as a start.

**Comment by bradberger** [comment] 2015-06-25 13:16
That sounds great. I started using this for a project that's not very active right now, so I haven't used it/tested it a lot, and no doubt your PR would be a better solution :smile:

**Comment by bradberger** [comment] 2015-08-24 17:21
I completely overhauled everything as I'm planning on using this in a new project, so I'm not sure that this applies anymore... so much has changed that it completely breaks the previous version. As I really have no intention of back-porting anything I'm going to close this pending any other feedback...

**Closed by bradberger** 2015-08-24 17:21 UTC
Labels: bug
